Streak
valeIT/valeIT.github.io pull request #101
Opened 2019-12-04 09:42 UTC by valeIT

2019-12-04 17:27 UTC, MsSlacker requested changes

2019-12-04 17:27 UTC, MsSlacker commented on _posts/2019-12-04-on-streaks.md
> +When I lost my first streak ever (on Duolingo 3 years ago) I quitted for 6 months, mostly because it was not my fault. Streaks on Duolingo are rather buggy and if you don't keep a streak freeze const
quitted - > quit

2019-12-04 17:27 UTC, MsSlacker commented on _posts/2019-12-04-on-streaks.md
> +With that I'm not trying to say that the streak is meaningless. It is not, but it should not become your only goal. It is just the mean to reach the goal.
mean - > byproduct?

2019-12-06 06:12 UTC, MsSlacker approved these changes

2019-12-06 06:13 UTC, MsSlacker approved these changes

2019-12-13 15:45 UTC, valeIT commented
Bad bot...

2019-12-13 15:48 UTC, merged