2020-01-02
valeIT/valeIT.github.io pull request #122
Opened 2020-01-01 17:33 UTC by valeIT

2020-01-02 07:04 UTC, MsSlacker requested changes

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +It did not pan out as planned. We now have more than 10 streaming subscriptions each one of them with their own original shows and exclusive publishing deals for specific movies and tv shows and we e
subscribptions - > subscriptions

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +It did not pan out as planned. We now have more than 10 streaming subscriptions each one of them with their own original shows and exclusive publishing deals for specific movies and tv shows and we e
non duoubtly - > no doubt

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +- The expanse on Netflix
AMAZON PRIME

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +- The expanse on Netflix
Plus capitalize it lol

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +- The expanse on Netflix
We don't really watch anything on Netflix besides black mirror

2020-01-02 07:04 UTC, MsSlacker commented on _posts/2020-01-02-streaming-cable.md
> +**Total $48.95** [^1]
Want Polish prices?

2020-01-02 20:21 UTC, valeIT commented on _posts/2020-01-02-streaming-cable.md
> +**Total $48.95** [^1]
not really xD just an average

2020-01-04 07:54 UTC, MsSlacker approved these changes

2020-01-04 07:56 UTC, merged