WIP: slack
valeIT/valeIT.github.io pull request #128
Opened 2020-01-09 19:28 UTC by valeIT

2020-01-12 20:39 UTC, MsSlacker requested changes

2020-01-12 20:39 UTC, MsSlacker commented on _posts/2020-01-10-communication-on-slack.md
> +At work whenever we don't need emails we use Slack. You can say we use it for everything. I guess most companies do the same nowadays. Some times though it is used too much and for the wrong use case
Sometimes should be together, right?

2020-01-12 20:39 UTC, MsSlacker commented on _posts/2020-01-10-communication-on-slack.md
> +Groups are great. When you have a discussion about something that relates to the whole project or part of it or in any other case that interests more than 1 person create a group for it. Try to avoid
strickly - > strictly?

2020-01-12 20:39 UTC, MsSlacker commented on _posts/2020-01-10-communication-on-slack.md
> +
tent - > tend

2020-01-13 17:26 UTC, valeIT commented on _posts/2020-01-10-communication-on-slack.md
> +At work whenever we don't need emails we use Slack. You can say we use it for everything. I guess most companies do the same nowadays. Some times though it is used too much and for the wrong use case
sure

2020-01-13 20:56 UTC, MsSlacker approved these changes

2020-01-13 20:56 UTC, merged