2020-02-08
valeIT/valeIT.github.io pull request #136
Opened 2020-02-08 19:11 UTC by valeIT

2020-02-15 19:46 UTC, MsSlacker requested changes

2020-02-15 19:46 UTC, MsSlacker commented on _posts/2020-02-08-new-language.md
> +I've been on and off trying to learn polish for the past few years with basically zero success. I know some basic words and phrases, but I wouldn't be able to hold my own even in basics conversations
P P P
PPPPPPPPPPPPPPPP

2020-02-22 19:40 UTC, valeIT commented on _posts/2020-02-08-new-language.md
> +I've been on and off trying to learn polish for the past few years with basically zero success. I know some basic words and phrases, but I wouldn't be able to hold my own even in basics conversations
Who cares... apparently you xD

2020-02-25 20:10 UTC, MsSlacker approved these changes

2020-02-25 20:21 UTC, merged