Create 2020-02-11-night-shift-f-lux.md
valeIT/valeIT.github.io pull request #138
Opened 2020-02-10 19:41 UTC by valeIT

2020-02-15 19:42 UTC, MsSlacker requested changes

2020-02-15 19:42 UTC, MsSlacker commented on _posts/2020-02-11-night-shift-f-lux.md
> +Night Shift from Apple has all the basics covered out: it shifts the hue of your screen to make it easier to the eyes during night time and has less adverse effects on your sleep cycle. I'm not sure
to the eyes - > for?

2020-02-15 19:42 UTC, MsSlacker commented on _posts/2020-02-11-night-shift-f-lux.md
> +Nowadays I'm still using f.lux instead of the default one since it provides way more customizabily while being free. The killer feature is being able to customize the hue to whatever you prefer from
customizabily - > customizability

2020-02-15 19:42 UTC, MsSlacker commented on _posts/2020-02-11-night-shift-f-lux.md
> +Nowadays I'm still using f.lux instead of the default one since it provides way more customizabily while being free. The killer feature is being able to customize the hue to whatever you prefer from
while still being free?

2020-02-15 19:42 UTC, MsSlacker commented on _posts/2020-02-11-night-shift-f-lux.md
> +Unfortunately on iOS you are forced to use Night Shift since due to Apple limitation an application like f.lux can't function on the platform. In the past when the iOS was very limited and jailbreaki
limitation - > s?

2020-02-22 19:46 UTC, valeIT commented on _posts/2020-02-11-night-shift-f-lux.md
> +Unfortunately on iOS you are forced to use Night Shift since due to Apple limitation an application like f.lux can't function on the platform. In the past when the iOS was very limited and jailbreaki
commas as well

2020-03-01 19:45 UTC, MsSlacker approved these changes

2020-03-01 19:48 UTC, merged