same direction
valeIT/valeIT.github.io pull request #45
Opened 2019-10-21 16:58 UTC by valeIT

2019-10-21 18:13 UTC, MsSlacker requested changes

2019-10-21 18:13 UTC, MsSlacker commented on _posts/2019-10-22-unity-same-directions.md
> +Doing this kind of targeting is easier than you might think It is sufficient to calculate the difference between your forward angle and the target. In my case the forward angle corresponds with the .
Missing a "."

2019-10-23 18:07 UTC, valeIT commented
@MsSlacker Looks good now? :)

2019-10-24 19:37 UTC, MsSlacker approved these changes

2019-10-24 19:42 UTC, merged