gitlab
valeIT/valeIT.github.io pull request #74
Opened 2019-10-31 17:58 UTC by valeIT

2019-11-01 20:05 UTC, MsSlacker requested changes

2019-11-01 20:05 UTC, MsSlacker commented on _posts/2019-11-03-migrating-to-gitlab.md
> +Gitlab Pages using Gitlab pipelines supports automatically pulling a GitHub repository and building it at each new commit. Exactly what I need. All the code will stay on GitHub to use its better ecos
Server or served?

2019-11-01 20:05 UTC, MsSlacker commented on _posts/2019-11-03-migrating-to-gitlab.md
> +This will tell gitlab to automatically build every commit on the master branch using jekyll. Go to the pipelines page in Gitlab after the first commit that includes this file to check if the shared G
"if it's not "

2019-11-02 09:04 UTC, valeIT commented on _posts/2019-11-03-migrating-to-gitlab.md
> +Gitlab Pages using Gitlab pipelines supports automatically pulling a GitHub repository and building it at each new commit. Exactly what I need. All the code will stay on GitHub to use its better ecos
served =)

2019-11-02 14:51 UTC, MsSlacker approved these changes

2019-11-02 14:52 UTC, merged