coffee
valeIT/valeIT.github.io pull request #79
Opened 2019-11-06 18:48 UTC by valeIT

2019-11-06 20:12 UTC, MsSlacker requested changes

2019-11-06 20:12 UTC, MsSlacker commented on _posts/2019-11-08-coffee.md
> +There are a lot of different kind of coffees, some are good, others just so so, and then there are the truly awful ones that make you wonder if whoever produced it even knew what coffee is.
Don't think it's countable? So no s?

2019-11-06 20:12 UTC, MsSlacker commented on _posts/2019-11-08-coffee.md
> +Being italian I have a pretty high quality standard for coffee so it has always been hard to find one that I really liked abroad. Fortunately in most Europe you can find Italian branded coffee, it us
Big I!

2019-11-06 20:12 UTC, MsSlacker commented on _posts/2019-11-08-coffee.md
> +If I can drink it whole without internally complaining it means it's actually quite good. Honestly I haven't found many of that quality abroad, only a handful of times.
No mention of terrible ones? Like the choco one you said about earlier?

2019-11-07 17:09 UTC, valeIT commented on _posts/2019-11-08-coffee.md
> +There are a lot of different kind of coffees, some are good, others just so so, and then there are the truly awful ones that make you wonder if whoever produced it even knew what coffee is.
Yeah, sounds bad

2019-11-07 17:27 UTC, MsSlacker approved these changes

2019-11-07 18:11 UTC, merged