WIP - unity
valeIT/valeIT.github.io pull request #83
Opened 2019-11-08 18:01 UTC by valeIT

2019-11-11 21:01 UTC, MsSlacker requested changes

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-11-unity-building-your-app.md
> +This initial configuration process is common to every platform and it is done insite Unity before exporting the application.
insite - > inside

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-11-unity-building-your-app.md
> +I read many tutorials and none of them worked. This is what worked for me on Mac OS:
This looks out of place after a :

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-11-unity-building-your-app.md
> +4. Yype: `/Users/USER/tizen-studio/tools/ide/bin/tizen.sh cli-config --global "default.profiles.path=/Users/USER/workspace/.metadata/.plugins/org.tizen.common.sign/profiles.xml"` changing `/Users/USE
Yype - > type

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-11-unity-building-your-app.md
> +- Go back to unity -> PlayerSettings -> Tizen and fill the field "Signing Profile Name" with  the name of your certificate
Double space after with?

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-11-unity-building-your-app.md
> +Note: If you have any third party Android or iOS plugins of any kind (analytics, ads, crash reporting, ...) the build will fail. The only solution I found is to create another project without them an
Can just do "look note for tizen"

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-12-unity-text-in-front-of-sprite.markdown
> +The first thought would be to have the text object be placed as children of the sprite so that it follows the sprite position as it moves around the scene. This way we avoid using the canvas and havi
Umm why it starts without an introduction...? What am I reading about o.o

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-12-unity-text-in-front-of-sprite.markdown
> +The first thought would be to have the text object be placed as children of the sprite so that it follows the sprite position as it moves around the scene. This way we avoid using the canvas and havi
syncronize - > synchronise

2019-11-11 21:01 UTC, MsSlacker commented on _posts/2019-11-12-unity-text-in-front-of-sprite.markdown
> +Note: For this method to work your text needs to be a children of the sprite so if you haven't already drag it on top of the sprite to make it a children.
children - > child

2019-11-12 14:16 UTC, valeIT commented on _posts/2019-11-12-unity-text-in-front-of-sprite.markdown
> +The first thought would be to have the text object be placed as children of the sprite so that it follows the sprite position as it moves around the scene. This way we avoid using the canvas and havi
synchronise  -> synchronize

2019-11-12 14:17 UTC, valeIT commented on _posts/2019-11-11-unity-building-your-app.md
> +Note: If you have any third party Android or iOS plugins of any kind (analytics, ads, crash reporting, ...) the build will fail. The only solution I found is to create another project without them an
Not sure, would seem weird imo. Copy pasting is not the best, but it is more clear...

2019-11-12 20:41 UTC, MsSlacker approved these changes

2019-11-12 20:41 UTC, merged