WIP - newmac
valeIT/valeIT.github.io pull request #92
Opened 2019-11-24 19:26 UTC by valeIT

2019-11-24 19:41 UTC, MsSlacker requested changes

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +I just bought a MacBook a few years ago so I'm not interested in this year's macbook pro, but if I did not I would have surely bought it. It still has a lot of problems, but finally even at Apple stu
A year ago. It's 2018 mbp...

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +I just bought a MacBook a few years ago so I'm not interested in this year's macbook pro, but if I did not I would have surely bought it. It still has a lot of problems, but finally even at Apple stu
Apple , (...) are ,

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +I just bought a MacBook a few years ago so I'm not interested in this year's macbook pro, but if I did not I would have surely bought it. It still has a lot of problems, but finally even at Apple stu
they have realised

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +I just bought a MacBook a few years ago so I'm not interested in this year's macbook pro, but if I did not I would have surely bought it. It still has a lot of problems, but finally even at Apple stu
buttlerfly - butterfly

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +It is astonishing that this needs to be in a list of pro for a laptop, but here we are. What a shame.
pro - > pros

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +- The touch id and off button is now more visible. I took a week to realize where it was when I bought the 2018 macbook pro.
just say "when I bought mine "

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +Finally we have a really good microphone already in our mac so during skype/slack/zoom calls we don't always have to use headphones + mic to get a decent audio. We will still need it to record a podc
time is not countable...

2019-11-24 19:41 UTC, MsSlacker commented on _posts/2019-11-25-new-macBook.md
> +The touchbar is still here, it seems that Apple won't go back on this. It is way worse than having physical keys and the missclicks are a lot. I even had to hide a few buttons so that they didn't mis
change "a lot" to something else

2019-11-25 20:07 UTC, valeIT commented on _posts/2019-11-25-new-macBook.md
> +I just bought a MacBook a few years ago so I'm not interested in this year's macbook pro, but if I did not I would have surely bought it. It still has a lot of problems, but finally even at Apple stu
> realised
realized is ok.

2019-11-26 20:08 UTC, MsSlacker submitted a review, later dismissed

2019-12-05 18:01 UTC, valeIT commented
Can this be merged?

2019-12-09 18:44 UTC, valeIT commented
> Can this be merged?

+1 :P

@MsSlacker

2019-12-18 16:35 UTC, merged